version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
        - echo Installing mkdocs
        - pip3 install mkdocs
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - cd mkd-blog
      - mkdocs build -d ../blog
      - cd ..
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
