version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
        - echo Installing mkdocs
        - pip3 install mkdocs
        - echo Installing requirements
        - pip3 install -r requirements.txt
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - if [[ "${INJECT_BUILD_FAILURE}" ]]; then exit 1; fi
      - cd mkd-blog
      - sed -i "s/##sed_date_here##/`date +"%Y-%m-%d %H:%M"`/" docs/index.md
      - sed -i "s;localhost.*;www.forshaw.tech/blog/;" mkdocs.yml
      - chmod 755 ../bin/insert-article-dates.sh && ../bin/insert-article-dates.sh
      - mkdocs build -d ../blog
      - cd .. && rm -r mkd-blog && rm -r sls && rm -r aws-cf    # Un-needed dirs
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
   - '*/**'
  # Define two artifacts here so we can deploy to 2 buckets
  secondary-artifacts:
    codebuildForshawTechArtifacts:
      files:
        - 'index.html'
        - 'assets/**'
    codebuildBlogArtifacts:
      files:
        - 'blog/**'
