version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
        - echo Installing mkdocs
        - pip3 install mkdocs
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - if [[ "${INJECT_BUILD_FAILURE}" ]]; then exit 1; fi
      - cd mkd-blog
      - sed -i "s/##sed_date_here##/`date +"%Y-%m-%d %H:%M"`/" docs/index.md
      - mkdocs build -d ../blog
      - cd ..
      - rm -r mkd-blog  # Un-needed
      - rm -r sls       # Un-needed
      - rm -r aws-cf    # Un-needed
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
