site_name: Develop Deploy Deliver
site_url: http://localhost:8000/

site_author: Richard Forshaw

theme:
    name: null
    custom_dir: cinder
    colorscheme: sunburst
    highlightjs: true

# Extra styling
extra_css:
    - "css/extra.css"

# custom scripts
extra_javascript:
    - "js/pageviews-api.js"


nav:
    - All Articles: 'articles.md'
    - Article Tags: 'tags.md'
    - 'about.md'
    - Contact: 'http://www.forshaw.tech/#ContactForm'

# For the sidebar message under nav items
custom_sidebar:
    image: "VTNM_Profile_2022.jpg"
    text: "A collection of articles on Software, Software Management and Technology. With a little Self-Development. Opinions expressed here are my own."
    announcement_text: "Currently available in Vietnam! For any consultancy or speaking opportunities, please contact me using the contact form."


plugins:
    - search
    - awesome-pages
    - blogging:
        time_format: '%Y-%m-%d'
        meta_time_format: '%Y-%m-%d'
        dirs:
          - blog/articles
        paging: false
        size: 5
        features:
          tags:
            insert: bottom
        show_total: false
        categories:
          - name: all
            time_format: '%Y-%m-%d'
            meta_time_format: '%Y-%m-%d'
            dirs:
              - blog/articles
            paging: true

markdown_extensions:
    - attr_list
