site_name: Develop Deploy Deliver
site_url: http://localhost:8000/

site_author: Richard Forshaw

theme:
    name: null
    custom_dir: cinder
    colorscheme: sunburst
    highlightjs: true

# Extra styling
extra_css:
    - "css/extra.css"

# custom scripts
extra_javascript:
    - "js/pageviews-api.js"
    - "js/share-click-handler.js"

nav:
    - All Articles: 'articles.md'
    - Article Tags: 'tags.md'
    - Book Reviews: 'books.md'
    - About This Blog: 'about.md'
    - Contact: 'http://www.forshaw.tech/#ContactForm'

# For the sidebar message under nav items
custom_sidebar:
    image: "VTNM_Profile_2022.jpg"
    text: "A collection of articles on Software, Software Management and Technology. With a little Self-Development. Opinions expressed here are my own."
    announcement_text: "Currently available in Sydney! For any consultancy, training or speaking opportunities, please contact me using the contact form."


plugins:
    - search
    - awesome-pages
    - social-buttons:
        default_message: "I found this interesting post on the Develop Deploy Deliver blog...\n"
        button_class: "share-button"
        apply_to_paths:
          - blog/articles
          - blog/books
        exclude_hashtags:
          - nontechnical
          - personal
        linked_in: {}
        twitter:
          button_share_callback: record_share
    - blogging:
        time_format: '%Y-%m-%d'
        meta_time_format: '%Y-%m-%d'
        dirs:
          - blog/articles
          - blog/books
        paging: false
        size: 6
        features:
          tags:
            insert: bottom
        show_total: false
        categories:
          - name: all_articles
            time_format: '%Y-%m-%d'
            meta_time_format: '%Y-%m-%d'
            dirs:
              - blog/articles
            paging: true

          - name: all_books
            time_format: '%Y-%m-%d'
            meta_time_format: '%Y-%m-%d'
            dirs:
              - blog/books
            paging: true

markdown_extensions:
    - attr_list
