site_name: Forshaw.Tech
site_url: http://www.forshaw.tech/blog/

site_author: Richard Forshaw

theme:
    name: null
    custom_dir: cinder
    colorscheme: sunburst
    highlightjs: true

markdown_extensions:
    - attr_list
