site_name: Forshaw.Tech
site_url: http://localhost:8000/

site_author: Richard Forshaw

theme:
    name: null
    custom_dir: cinder
    colorscheme: sunburst
    highlightjs: true

# Experimental styling
# extra_css:
#     - "css/extra.css"

# custom scripts
extra_javascript:
    - "js/pageviews-api.js"


nav:
    - 'index.md'
    - All Articles: 'articles.md'
    - Article Tags: 'tags.md'
    - 'about.md'
    - Contact: 'http://www.forshaw.tech/#ContactForm'

# For the sidebar message under nav items
sidebar_info_message: "Available in Vietnam! For any consultancy or speaking opportunities, please contact me using the contact form."

plugins:
    - search
    - awesome-pages
    - blogging:
        time_format: '%Y-%m-%d'
        meta_time_format: '%Y-%m-%d'
        dirs:
          - articles
        paging: false
        size: 5
        features:
          tags:
            insert: bottom
        show_total: false
        categories:
          - name: all
            time_format: '%Y-%m-%d'
            meta_time_format: '%Y-%m-%d'
            dirs:
              - articles
            paging: true

markdown_extensions:
    - attr_list
