# Template for defining Website and Continuous Deployment pipeline
AWSTemplateFormatVersion: 2010-09-09

Description: Stack for running the resume website

Parameters:
  WebsiteName:
    Type: String
    Description: The canonical name of the website, used to prefix all associated infrastructure.
    MinLength: 5
    MaxLength: 20
    AllowedPattern: '[a-zA-Z0-9\-]*'
  WebsiteURL:
    Type: String
    Description: The intended URL of the website. This is required for accessing S3 website with custom domains.
    MinLength: 7
    MaxLength: 40
    AllowedPattern: '[a-zA-Z0-9\-\.]*'
  GitHubOAuthAccessToken:
    Type: String
    Description: OAuth Token to access the GitHub repo
    MinLength: 20
    AllowedPattern: '[a-zA-Z0-9]*'

Resources:
  TechWebsiteS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref WebsiteURL
      WebsiteConfiguration:
        IndexDocument: index.html

  TechWebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: TechWebsiteS3Bucket
      PolicyDocument:
        Statement:
          -
            Sid: "PublicReadGetObject"
            Effect: "Allow"
            Principal: "*"
            Action:
              - "s3:GetObject"
            Resource: !Join [ '', ['arn:aws:s3:::', !Ref WebsiteURL, '/*']]

  TechWebsiteHostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      HostedZoneConfig:
        Comment: "Domain registered at hover.com"
      Name: !Ref WebsiteURL

  TechWebsiteRouting:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId:
        Ref: TechWebsiteHostedZone
      Name: !Ref WebsiteURL
      Comment: Alias records for S3 website bucket
      Type: A
      AliasTarget:
        DNSName: s3-website-ap-southeast-1.amazonaws.com  # From AWS Service Endpoint Documentation
        HostedZoneId: Z3O0J2DXBE1FTB                      # From AWS Service Endpoint Documentation


  WebsiteDeploymentRole:
    Type: AWS::IAM::Role
    Properties:
      Description: Role to allow deployment of website data from Source Control to S3
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      RoleName: !Join [ '', [!Ref WebsiteName, '-website-deployment-role']]

  WebsiteDeploymentArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join [ '', [!Ref WebsiteName, '-website-deploy-artifact-bucket']]

  WebsiteDeploymentPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Join [ '', [!Ref WebsiteName, '-website-deployment-pipeline']]
      RoleArn: !GetAtt WebsiteDeploymentRole.Arn
      ArtifactStore:
        Type: S3
        Location:
          Ref: WebsiteDeploymentArtifactBucket
      Stages:
        -
          Name: Source
          Actions:
            -
              Name: GithubSourceAction
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: '1'
              OutputArtifacts:
                - Name: WebsiteSource
              Configuration:
                Owner: RichardForshaw
                Repo: resume
                Branch: master
                PollForSourceChanges: false
                OAuthToken:
                  Ref: GitHubOAuthAccessToken
              RunOrder: 1
        -
          Name: Deploy
          Actions:
            -
              Name: S3DeploymentAction
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: S3
                Version: '1'
              InputArtifacts:
                - Name: WebsiteSource
              Configuration:
                BucketName:
                  Ref: TechWebsiteS3Bucket
                Extract: true
              RunOrder: 1

  WebsiteDeploymentWebhook:
    Type: AWS::CodePipeline::Webhook
    Properties:
      Name: ResumeRepoUpdatedWebhook
      Authentication: GITHUB_HMAC
      Filters:
        -
          JsonPath: "$.ref"
          MatchEquals: refs/heads/{Branch}
      AuthenticationConfiguration:
        SecretToken:
          Ref: GitHubOAuthAccessToken
      TargetPipeline:
        Ref: WebsiteDeploymentPipeline
      TargetPipelineVersion: 1
      TargetAction: GithubSourceAction

