AWSTemplateFormatVersion: 2010-09-09

Description: Cloudformation for accounts and roles within the forshaw.tech account

Resources:
  ReceiptTrackingDeveloperGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: ReceiptTrackingDeveloperGroup
      Policies:
        - PolicyName: AssumeRolePolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Resource:
                  - 'arn:aws:iam::801774630682:role/Receipt-Tracking*'
                Action:
                  - 'sts:AssumeRole'

  ServerlessDeploymentGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: ServerlessDeploymentGroup
      Policies:
        - PolicyName: ServerlessDeploymentPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Resource:
                  - 'arn:aws:cloudformation:us-west-2:801774630682:stack/*/*'
                Action:
                  - 'cloudformation:DescribeStack*'
                  - 'cloudformation:CreateStack'
                  - 'cloudformation:UpdateStack'
                  - 'cloudformation:DeleteStack'
                  - 'cloudformation:ListStack*'
              - Effect: Allow
                Action:
                  - 'cloudformation:ValidateTemplate'
                Resource:
                  - '*'
              - Effect: Allow
                Action:
                  - 'lambda:*'
                Resource:
                  - 'arn:aws:lambda:*:801774630682:function:*'
              - Effect: Allow
                Resource:
                  - !GetAtt TechWebsiteServerlessDeploymentRole.Arn
                Action:
                  - 'sts:AssumeRole'
                  - 'iam:PassRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

  ReceiptTrackingDeveloperRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: Receipt-Tracking-Developer-Role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - 'arn:aws:iam::801774630682:root'
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess
        - arn:aws:iam::aws:policy/AmazonSESFullAccess
        - arn:aws:iam::aws:policy/AmazonSNSFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

  ReceiptBotServerlessDeploymentRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: Receipt-Bot-Serverless-Deploy-Role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - 'arn:aws:iam::801774630682:root'
              Service:
                - 'cloudformation.amazonaws.com'
                - 'lambda.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: ServerlessDeployPolicies
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow   # Allow all IAM actions to roles prefixed with sls-
                Resource:
                  - 'arn:aws:iam::801774630682:role/sls-*'
                Action:
                  - 'iam:*'
              - Effect: Allow   # Allow all S3 actions to buckets prefixed with sls-
                Resource:
                  - 'arn:aws:s3:::sls-*'
                Action:
                  - 's3:*'
              - Effect: Allow   # Allow all lambda & iam actions to functions prefixed with sls-
                Resource:
                  - 'arn:aws:lambda:*:801774630682:function:sls-*'
                Action:
                  - 'lambda:*'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess

  TechWebsiteServerlessDeploymentRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: Tech-Web-Serverless-Deploy-Role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - 'arn:aws:iam::801774630682:user/S3-website-access'
              Service:
                - 'cloudformation.amazonaws.com'
                - 'lambda.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: ServerlessDeployPolicies
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow   # Allow all IAM actions to roles prefixed with service
                Resource:
                  - !Sub 'arn:aws:iam::${AWS::AccountId}:role/wwwstatuscheck-*'
                  - !Sub 'arn:aws:iam::${AWS::AccountId}:role/sls-page-tracker-*'
                  - !Sub 'arn:aws:iam::${AWS::AccountId}:role/Tech-Web-Serverless-Deploy-Role'
                Action:
                  - 'iam:*'
              - Effect: Allow   # Allow all S3 actions to buckets prefixed with service. Note this is for code deployment.
                Resource:
                  - 'arn:aws:s3:::wwwstatuscheck-*'
                  - 'arn:aws:s3:::sls-page-tracker-*'
                Action:
                  - 's3:*'
              - Effect: Allow   # Allow all lambda & iam actions to functions prefixed with service
                Resource:
                  - !Sub 'arn:aws:lambda:ap-southeast-1:${AWS::AccountId}:function:wwwstatuscheck-*'
                  - !Sub 'arn:aws:lambda:ap-southeast-1:${AWS::AccountId}:function:sls-page-tracker-*'
                Action:
                  - 'lambda:*'
              - Effect: Allow   # Allow all Dynamo actions
                Resource:
                  - !Sub 'arn:aws:dynamodb:ap-southeast-1:${AWS::AccountId}:table/PageTrackTable'
                Action:
                  - 'dynamodb:*'
        - PolicyName: S3CustomConfigurationPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow   # Allow the logs bucket to be configured
                Resource:
                  - 'arn:aws:s3:::logs.forshaw.tech'
                Action:
                  - 's3:getBucket*'
                  - 's3:putBucket*'
        - PolicyName: EventsPolicies
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow   # Allow all events (for scheduling) actions to functions prefixed with service
                Resource:
                  - 'arn:aws:events:ap-southeast-1:801774630682:rule/wwwstatuscheck-*'
                Action:
                  - 'events:*'
        - PolicyName: APIGatewayPolicies
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow   # Allow all operations to API gateway to APIs prefixed with service
                Action:
                  - 'apigateway:*'
                Resource:
                  - !Sub 'arn:aws:apigateway:ap-southeast-1:${AWS::AccountId}:/*'
                  - 'arn:aws:apigateway:ap-southeast-1::/tags/*'
                  - 'arn:aws:apigateway:ap-southeast-1::/apis/*'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess

