AWSTemplateFormatVersion: 2010-09-09

Description: Cloudformation for accounts and roles within the forshaw.tech account

Resources:
  ReceiptTrackingDeveloperRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: Receipt-Tracking-Developer-Role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - 'arn:aws:iam::801774630682:root'
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess
        - arn:aws:iam::aws:policy/AmazonSESFullAccess
        - arn:aws:iam::aws:policy/AmazonSNSFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

